language: node_js
node_js:
  - "6"
  - "6.1"
cache:
  directories:
    - node_modules
    - $(npm config get prefix)/node_modules
script: "npm run build && npm run test-ci && npm run coverage:remap"
after_script: "npm install coveralls && cat ./coverage/lcov.info | coveralls"